name: Build SFML Game (Windows, macOS & Ubuntu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install sfml --version=2.5.1 -y

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install sfml@2

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests (if any)
        run: ctest --test-dir build || echo "No tests found"
